# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "mpt3sas" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c8f67be5-9697-4334-ae7d-46d4b7f3074d";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2657-7FF0";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # fileSystems."/srv" = {
  #   device = [
  #     "/dev/disk/by-id/wwn-0x5000cca2532adf50"
  #     "/dev/disk/by-id/wwn-0x5000cca2532b7608"
  #     "/dev/disk/by-id/wwn-0x5000cca2532c3214"
  #     "/dev/disk/by-id/wwn-0x5000cca253326bd0"
  #     "/dev/disk/by-id/wwn-0x5000cca2709aef7c"
  #     "/dev/disk/by-id/wwn-0x5000cca2709f77ac"
  #     "/dev/disk/by-id/wwn-0x5000cca2709f7dc4"
  #     "/dev/disk/by-id/wwn-0x5000cca270a11468"
  #   ];
  # };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20u5u3.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens260.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens260d1.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens865.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens865d1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
