creation_rules:
  - path_regex: '\.yaml$'
    age: >-
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHZSyzWJCfFzGlzXHp1Uby6ayc7vUegexMet4ioKj1Cx,
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDbh3gdpIuefWXTHmNzQCn7gvTbwTUBJ1DGjOtTgrWj8,
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOen0Hh9uoJlT9ikRmc9dZQfsjMtBc2v7PNIHyf0KSNh,
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICyTxPV3S7ms0AJ0tduI3aJP3o2TJCnkirWKaj5i1+DW,
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHBzpC6FBOKNzO6AfdfGna6MLRg0cf+jhr+DgUwQqU1W
