apiVersion: ENC[AES256_GCM,data:sHY=,iv:/qaygBt8nladzMk5HK1JduYvnf6SI3vhD7Vgr6NmD00=,tag:lW/OS9FPEX+iNpjV00ZXRg==,type:str]
kind: ENC[AES256_GCM,data:9qbpJtve,iv:yUJxv8c0MDxAQ7ivvYv+ewoEdNe1y4IhqiWnTvz67uo=,tag:/p5K9f1tbBImXLcaOfTiqQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AS4gkxoO9y4FQQ7P,iv:tLHDFwEs5CRvH4Hdd2UVIjEUD2csJDvYNf02HDMcn9Y=,tag:qo7lZWq3M52/L8jORfz80w==,type:str]
type: ENC[AES256_GCM,data:00C/la7h,iv:HGs3mUcHo6NO9rJzsPUW8ufREd1LtAFR/CjLBuy+fkQ=,tag:PzJGUsBKE17schPghLE2Eg==,type:str]
stringData:
    mysql_password: ENC[AES256_GCM,data:fOLZFc+XTNy1IM4pQfsj7pRFL9JYN/KGVzEkTDFQEJY=,iv:u9gs3t9N5tmJ7QXxiuk2cmIuSQbgrUYckF1xpKkzBrg=,tag:F41QcgjQhZoWfGw4G9T2VA==,type:str]
    mysql_root_password: ENC[AES256_GCM,data:4NSloZzv+tTxuI51ieweAKZyy8t1TXL4zXlKTCSgZsk=,iv:qCBcAQtQ0ALu+DyXYKtfa7yEIu+dFerM0N4CNbkyaNA=,tag:ZiKsNtlk0HAyKjekRdFE1Q==,type:str]
    mw_secret_key: ENC[AES256_GCM,data:Qp7RcUz/xOiaUH+owvOZfNE4MsoOcwazP0IP3hzXwVt/gD/RlwZtZ4CSv6xXDbf6akL8ef5Dt62/MNmXm/Tx3g==,iv:Y5vf7ENyNARgYcmiUO6mTQs8do9lyZNnk92oPz3zlFI=,tag:5L6Mg6QoxDjAZY9eeiXUVg==,type:str]
    mw_upgrade_key: ENC[AES256_GCM,data:S4GrlmG3cpJsJSA8yKWbFw==,iv:p1Xy5vqGeXMnchS+yr9tTTJP5Bl96k9yzauMU8D7AAo=,tag:m0aj9h6Wje+tAdbmttzF2Q==,type:str]
    smtp_password: ENC[AES256_GCM,data:lyS8O1qbyPucthZruLdP8s+8vsur7uEY81L9K8bfd86PXf0C,iv:BehZTannUEYTbD6xcx+KOLfBiTDIfxMwMPi9LqXJN0g=,tag:jyelAxt70eNP8Ax6VbHShw==,type:str]
    odic_google_id: ENC[AES256_GCM,data:JaCpK/2O22vbkOvXJcD47cVihtBAfoKTnUScXIITw7Qu1YdkPwNPwvYUMZEw+PUBO9FrBTPo/9kjP+tlxNYC6BizRoaYRGfK,iv:WDJf0QGIOv4iv6b8Mdi4+/r6JuWFFurIZ+bhvJeaQsE=,tag:nbnK65I8FeQUgFk2/1OA1g==,type:str]
    odic_google_secret: ENC[AES256_GCM,data:CRp3Uz3aUHYojSqwT6qEDGEaJJq9Cod+,iv:JL9KNdqQ6GYZRlC/BfWuKellK7bu51/HGSPRR5Uhbfo=,tag:HlB/GDl/z9aYG7m2duYU9g==,type:str]
    dex_wiki_secret: ENC[AES256_GCM,data:Se4DSaXkLU9EEmLUk9NgaxvwLhlrIPM2Z6YETWDSyjQ=,iv:sbI8Eoe3xxGA+4mKR8rUwfkIukoBGbkUlQ4FN1+67qk=,tag:QBPSJONop0l+omkL4GzkxA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHZSyzWJCfFzGlzXHp1Uby6ayc7vUegexMet4ioKj1Cx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFNrd1pqUSBQTC9a
            UGpYVyt4RHEwYTBBNFZtaVU0MDJKQmlraE9EcE5remNCQ2ZxamdzCjV2Mm14YUZF
            ZE9SUmN3SUFKQ1YvQmxjR2ljbE1BNlhWNHZWcmloQmJSSlEKLS0tIFN4emZ6S3R3
            RWlmRTQwa3MxR3JmaGNUenhQNGQ0UW9XQ3VmSEwvLzhlUEEKaYGhdgrkgD9uiuB9
            T+PSb4v3SJkNxM7nzerHYxxYPci5YLq8Xod5PKPB+O8M5Rj/HNFa0Xg+icZ8ynUj
            D2PW/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDbh3gdpIuefWXTHmNzQCn7gvTbwTUBJ1DGjOtTgrWj8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHNTZXNQdyBEeFgv
            Z2R0NXhLSkpXTzFJZXJ2SkJCeElUVjBMT2x1dTErN0FZRjI2aVZBCjVUdUZFZUdU
            eDJrbkpoaDJkbGZFZEYrYTh5cEY2clVEWlNPcUU3NS9LTjgKLS0tIHp6SHhFSlQ3
            S1hzVjI0SkJWcEdnQnp2VytqTXVkcHBYaW5xR1Znb3RoTW8KnqleS1vycfQkj2Oh
            AujhvN5m1HlFAyRcc/JKBbBjC8AMTshVorQYkMBeaeu2DQVpM9w8OCwMXQrKF+mG
            S8vqEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOen0Hh9uoJlT9ikRmc9dZQfsjMtBc2v7PNIHyf0KSNh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IC9TdzZJUSBtcm9N
            Q21QRG1meGMvMEFZd1pHQUNRV2o2NXN3SmtNOEZnQ3IzYVhUK1FrClNlU2ljRXpQ
            RjhFWlhXUzdDT3dQUEFNaXhGNW1uQk5DSWU0RnEvRDJZNUUKLS0tIFk5T0JkRnFW
            YUpWTEpYeUpDOG5xWFVCOUI0cWw1dFBJblJ4STBobThsSlkKAyf1lbrCxMRYl2DO
            GLip3N4KcfWnN5EFgSWqPH3d4qKAVPIBL8Lr61OVDQx0U90b8w4Qwvsq3qinNAey
            yShoWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICyTxPV3S7ms0AJ0tduI3aJP3o2TJCnkirWKaj5i1+DW
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFlPcGY3USBJcVF3
            OFBjK3JqL2w3dnI1ZHNjUVlrSHNOM0ZDNlJ5QndudjNEeWdiMEJjCjlabHcxVDNz
            Z3o4cEFuT0dCdU1aRWRKc01QbFpVNFNtNytSbnMrRlBBMkEKLS0tIDgwTVc1Wlky
            a29ESFZJTVVNWXcvYk9oY2VtVEI1cWlDVWx6MkVYNFdKRHMKjVHBp+weGevvFT1X
            xccWRa8UL1LyfqrytCAn0uS2tXRGbmTqShpMJX8BeQma+p09ria4Xu4cUedCq+58
            cjzCUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHBzpC6FBOKNzO6AfdfGna6MLRg0cf+jhr+DgUwQqU1W
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdZWjVDUSBwbEYv
            TG1RNzRWYm9CM3ZEMEkrN1QvR01zamluOEdQWW9Oa2wvKzd6QUNVCmM0SGVqRitq
            MEEvNHRpYWFBa0J0MnFvNHRtNVNnTDFBS0w0dElHY0dtZ1kKLS0tIDd6MFRYbTVO
            S004bFk5Mm1Ham9uL0FDTHQwNkZUMER6NUxiZ0tPTXhOL1EK5ImrVb1h0u78XdYZ
            t+U1O8C95Xud7/Um19li30swm0iCpi206nuFRQlGv8ipAfvfp6n7m97HkEi6Qu+1
            62UPpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T02:20:25Z"
    mac: ENC[AES256_GCM,data:L+jqSCJAcOB9V3ndbBPC+K/wvsh8uR69qfgEoPUaexVX++0Dw44bJUkOw1zsktHO1lr3prjIZ74A9TojG1jq67nN1rm6NRxNCkm4CvtGOyTIL5IFz3eqkSMSQniQVeL/WGpTR1r8VlPxFRZyDYKxFTvuIwtRB0x0Ujl8sjILlGc=,iv:7i/XSs3ZYTVcvSeHSsr+L0Pd0rumpuaFTYF6cK7KrBY=,tag:lG5MZnylwPGrFs8+nUQT5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
