# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ehci_pci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "nfs" ];
  boot.swraid.enable = true;

  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "nodev";
    mirroredBoots = [
      {
        devices = [
          "/dev/disk/by-id/ata-SAMSUNG_SSD_PB22-JS3_FDE_TM_128GB_YCB310S926SY926A9648-part1"
          "/dev/disk/by-id/ata-SAMSUNG_SSD_PB22-JS3_FDE_TM_128GB_YCB310S926SY926A9650-part1"
        ];
        path = "/boot";
      }
    ];
  };
  boot.loader.efi.canTouchEfiVariables = false;


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/73e3f9e4-d28d-4bfe-9a59-8849e36ef295";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/73e3f9e4-d28d-4bfe-9a59-8849e36ef295";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=home" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/73e3f9e4-d28d-4bfe-9a59-8849e36ef295";
      fsType = "btrfs";
      options = [  "compress=zstd" "subvol=var" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/73e3f9e4-d28d-4bfe-9a59-8849e36ef295";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=nix" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/73e3f9e4-d28d-4bfe-9a59-8849e36ef295";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9210-B8CC";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}